#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=always

spring.profiles.active=local
security.api-key=bQ5xq1XWT9l0GSAs1Fz0BtfJbybndJlMQ4f1XToGxSmlpu3bTaktrR9D2M_4rB0vnvhFX6qDuwT3BlbkFJ8fykyIlndPTzJTicpy2v6XxYpnYeJQ7KBe5gsk8gCxJrag6r5UNKH38KRU9e7HZGEGheLl0dUA
security.client.id=tokenization-client
security.jwt.secret=mysuperlongsecretkeythatismorethan32characterslong1234567890
security.jwt.expiration-ms=300000

spring.kafka.bootstrap-servers: localhots:9002

# logging properties
logging.level.org.springframework.security=DEBUG
